# LuaCord Plugin Wrapper Template
# These values will be replaced by the JAR generator

name: PluginNamePlaceholder
version: VersionPlaceholder
author: AuthorPlaceholder
description: DescriptionPlaceholder
main: io.luacord.connector.PluginConnector
api-version: 1.13

# Note: We do NOT use 'depend: [LuaCord]' because we want
# to show a helpful error message if LuaCord is missing